name: macOS check minimum target
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Switch Xcode version from 15.2 to 14.1
        run: sudo xcode-select -s /Applications/Xcode_14.1.0.app
      - name: Check minimum target deployment target of macOS
        run: cat $(xcrun --sdk macosx --show-sdk-path)/SDKSettings.json | grep "MinimumDeploymentTarget"
      - name: Print current minimum target value of default
        run: echo $MACOSX_DEPLOYMENT_TARGET
